### ISSUE TITLE
Want to compare the current opened file with clipboard

### ISSUE THREAD

**Issue by Wanzyee** [heku/Kool.VsDiff#1]
Hi, heku,

Thanks for your great extension.

If you're willing, I'd like to compare the current opened file with clipboard.
Maybe there's a command on the file tab context menu or main menu to execute.

If so, I can compare the current file without accessing the Solution Explorer.
Furthermore, I can compare an external file which doesn't belong the solution.

Thank you again, Regards,
Wanzyee

**Comment by heku** [comment]
Thanks for your feedback, sounds good, I will add this feature.

**Comment by heku** [comment]
Hi, I added the menu but I didn`t publish to marketplace yet, you can have a try the CI build https://ci.appveyor.com/project/heku/kool-vsdiff/branch/dev/artifacts.

**Comment by heku** [comment]
Hi @Wanzyee, thank you for your feedback again, now this feature has been released.

**Comment by Wanzyee** [comment]
AWESOME !!!
