### ISSUE TITLE
Focusing VS Search (Ctrl+Q) causes an error dialog when no files are open

### ISSUE THREAD

**Issue by olegtk** [heku/Kool.VsDiff#2]
See https://developercommunity.visualstudio.com/t/Quick-Search-gives-immediate-error-when-/1374751

We identified the issues is caused by NullReferenceException in DiffClipboardWithCodeCommand.OnBeforeQueryStatus() and then BaseCommand.OnBaseBeforeQueryStatus() showing an error dialog.

Please don't show any dialogs during QueryStatus calls, they are intended to be very fast and have no side effects except modifying command state.
Thanks!

Name
--
Throw(System.NullReferenceException) Object reference not set to an instance of an object.
+ clr!EtwCallout
+ clr!CoTemplate_zzpqhh
+ clr!ETW::ExceptionLog::ExceptionThrown
+ clr!COMPlusThrowCallback
+ clr!Thread::StackWalkFramesEx
+ clr!Thread::StackWalkFrames
+ clr!CPFH_RealFirstPassHandler
+ clr!CPFH_FirstPassHandler
+ clr!_COMPlusFrameHandler
+ clr!_COMPlusFrameHandlerRevCom
+ ntdll!ExecuteHandler2
+ ntdll!ExecuteHandler
+ ntdll!KiUserExceptionDispatcher
+ Kool.VsDiff!DiffClipboardWithCodeCommand.OnBeforeQueryStatus
|+ Kool.VsDiff!BaseCommand.OnBaseBeforeQueryStatus
...

**Comment by heku** [comment]
Thanks for your suggestion and code fix, I'll merge it soon.
