### ISSUE TITLE
Could we let it support edit left side window ?

### ISSUE THREAD

**Issue by huangjinshe** [heku/Kool.VsDiff#8]
When Compare 2 files, the left side window is locked, can't edit. Is that possible that we could let it editable like right side too?

**Comment by heku** [comment]
Hi @huangjinshe, basically no I think, this extension just invokes the visual studio's builtin diff tool, which seems always treat the left side one as readonly. A workaround is you could configure a custom diff tool via 'options | kool | VS Diff', if the custom tool supports that, you could have a try.
